### Health check
GET http://localhost:8080/api/health


### About
GET http://localhost:8080/api/about


### Get all assets
GET http://localhost:8080/api/assets


### Get one asset
GET http://localhost:8080/api/assets/A001


### Get asset that does not exist
GET http://localhost:8080/api/assets/A999


### Create a valid asset
POST http://localhost:8080/api/assets
Content-Type: application/json

{
  "assetTag": "LAP-2026-004",
  "name": "MacBook Air M5",
  "category": "Laptop",
  "serialNumber": "SN-LAP-004",
  "location": "HQ Level 67"
}


### Create an invalid asset
POST http://localhost:8080/api/assets
Content-Type: application/json

{
  "assetTag": "",
  "name": "",
  "category": "",
  "serialNumber": "",
  "location": ""
}
